# Generated by Django 5.2.8 on 2025-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLead',
            fields=[
            ],
            options={
                'verbose_name': 'Chatbot Lead',
                'verbose_name_plural': 'Chatbot Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leads.lead',),
        ),
        migrations.CreateModel(
            name='WebsiteLead',
            fields=[
            ],
            options={
                'verbose_name': 'Website Lead',
                'verbose_name_plural': 'Website Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leads.lead',),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='website', max_length=100),
        ),
    ]
