# Generated by Django 5.2.8 on 2025-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_chatbotlead_websitelead_lead_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
