# Generated by Django 5.2.8 on 2025-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sub_services',
            field=models.TextField(blank=True, help_text='Comma-separated list of selected sub-services'),
        ),
        migrations.AddField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, help_text='When is the service required?', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, help_text='Main Service Category', max_length=200),
        ),
    ]
