# Generated by Django 5.2.8 on 2026-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('forwarded', 'Forwarded'), ('done', 'Done'), ('canceled', 'Canceled'), ('spam', 'Spam')], default='new', max_length=20),
        ),
    ]
