# Generated by Django 5.2.8 on 2025-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Need a Custom Solution?', max_length=255)),
                ('text', models.TextField(default='Our experts are ready to help you design, deploy, and optimize your finance strategy.')),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
            ],
            options={
                'verbose_name': 'Bottom CTA',
                'verbose_name_plural': 'Bottom CTA',
            },
        ),
        migrations.CreateModel(
            name='ServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Services', max_length=255)),
                ('subtitle', models.TextField(default='End-to-end financial solutions tailored for your growth.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
