# Generated by Django 5.2.8 on 2025-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='CheckCircle', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Settings', help_text='Lucide Icon Name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_page/testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='servicehero',
            name='cta_text',
            field=models.CharField(default='Explore Services', max_length=50),
        ),
        migrations.AddField(
            model_name='servicehero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_page/'),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='button_text',
            field=models.CharField(default='Get a Custom Quote', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='text',
            field=models.TextField(default='Book a consultation with our experts today.'),
        ),
        migrations.AlterField(
            model_name='servicecta',
            name='title',
            field=models.CharField(default='Ready to optimize your finance?', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicehero',
            name='subtitle',
            field=models.TextField(default='Comprehensive financial solutions tailored for your business growth.'),
        ),
        migrations.AlterField(
            model_name='servicehero',
            name='title',
            field=models.CharField(default='Our Expertise', max_length=255),
        ),
    ]
