# Generated by Django 5.2.8 on 2026-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='XpertAI Global', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('show_announcement', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, default='Welcome to our new website!', max_length=500)),
                ('announcement_link', models.CharField(blank=True, default='#', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
