# Generated by Django 5.2.8 on 2026-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='nav_about_label',
            field=models.CharField(default='About', max_length=50),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='nav_careers_label',
            field=models.CharField(default='Careers', max_length=50),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='nav_cta_label',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='nav_resources_label',
            field=models.CharField(default='Resources', max_length=50),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='nav_services_label',
            field=models.CharField(default='Services', max_length=50),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='nav_solutions_label',
            field=models.CharField(default='Solutions', max_length=50),
        ),
    ]
