# Generated by Django 5.2.8 on 2025-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the section.', max_length=200)),
                ('content', models.TextField(help_text='The main content of the section. Can contain HTML.')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the section.', null=True, upload_to='homepage_sections/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order of the section.')),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order'],
            },
        ),
    ]
