# Generated by Django 5.2.8 on 2025-11-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepagesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSection',
        ),
    ]
