# Generated by Django 5.2.8 on 2026-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_bio_userprofile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leads_notification_email',
            field=models.EmailField(blank=True, help_text='Email to receive lead notifications', max_length=254, null=True),
        ),
    ]
