# Generated by Django 5.2.8 on 2025-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('features', 'Features'), ('stakeholders', 'Stakeholders'), ('lead_system', 'Lead System'), ('blog', 'Blog'), ('resources', 'Resources'), ('careers', 'Careers'), ('contact', 'Contact')], max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'section'],
                'unique_together': {('page', 'section')},
            },
        ),
    ]
