# Generated by Django 5.2.8 on 2025-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_seed_additional_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('features', 'Features'), ('stakeholders', 'Stakeholders'), ('lead_system', 'Lead System'), ('blog', 'Blog'), ('resources', 'Resources'), ('careers', 'Careers'), ('contact', 'Contact'), ('portfolio', 'Portfolio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(help_text='Available sections per page → Home: hero_title, hero_text, hero_image, services_title, service1_title, service1_desc, service2_title, service2_desc, service3_title, service3_desc, cta_title, cta_button | Contact: contact_header, contact_subtext, form_title, info_title, info_text, address, email, phone, map_link, map_button, cta_title, cta_button | About: hero_title, hero_text, mission_title, mission_text, vision_title, vision_text, values_title, values_text, cta_title, cta_text | Services: hero_title, hero_text, service_card_1_title, service_card_1_desc, service_card_2_title, service_card_2_desc, service_card_3_title, service_card_3_desc, service_card_4_title, service_card_4_desc, service_card_5_title, service_card_5_desc, service_card_6_title, service_card_6_desc, cta_title, cta_text, cta_button | Features: hero_title, hero_text, feature_card_1_title, feature_card_1_desc, feature_card_2_title, feature_card_2_desc, feature_card_3_title, feature_card_3_desc, feature_card_4_title, feature_card_4_desc, feature_card_5_title, feature_card_5_desc, feature_card_6_title, feature_card_6_desc | Stakeholders: hero_title, hero_text, stakeholder_card_1_title, stakeholder_card_1_desc, stakeholder_card_1_icon, stakeholder_card_2_title, stakeholder_card_2_desc, stakeholder_card_2_icon, stakeholder_card_3_title, stakeholder_card_3_desc, stakeholder_card_3_icon, stakeholder_card_4_title, stakeholder_card_4_desc, stakeholder_card_4_icon, stakeholder_card_5_title, stakeholder_card_5_desc, stakeholder_card_5_icon, stakeholder_card_6_title, stakeholder_card_6_desc, stakeholder_card_6_icon | Resources: hero_title, hero_text, downloads_title, resource_card_1_title, resource_card_1_desc, resource_card_1_link, resource_card_2_title, resource_card_2_desc, resource_card_2_link, resource_card_3_title, resource_card_3_desc, resource_card_3_link, blog_highlight_title | Lead_system: hero_title, hero_text, cta_title, cta_text | Careers: hero_title, hero_text, openings_title, job_card_1_title, job_card_1_dept, job_card_1_location, job_card_1_type, job_card_2_title, job_card_2_dept, job_card_2_location, job_card_2_type, job_card_3_title, job_card_3_dept, job_card_3_location, job_card_3_type, form_title, form_subtext | Blog: hero_title, hero_text', max_length=100),
        ),
    ]
