# Generated by Django 5.2.8 on 2025-11-21 12:00

from django.db import migrations, models
from cms.sections import get_help_text


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(help_text=get_help_text(), max_length=100),
        ),
    ]
