# Generated by Django 4.1.13 on 2024-05-23 12:39

from django.db import migrations

def add_new_homepage_sections(apps, schema_editor):
    SiteContent = apps.get_model('cms', 'SiteContent')
    
    new_sections = [
        {"page": "home", "section": "portfolio_title", "title": "Portfolio Highlights", "content": "A glimpse into some of our successful projects."},
        {"page": "home", "section": "case_studies_title", "title": "Case Studies", "content": "In-depth looks at how we've helped our clients succeed."},
        {"page": "home", "section": "our_process_title", "title": "Our Process", "content": "Our streamlined process for delivering exceptional results."},
        {"page": "home", "section": "testimonials_title", "title": "What Our Clients Say", "content": "Read what our clients have to say about their experience working with us."},
        {"page": "home", "section": "blog_posts_title", "title": "Latest From The Blog", "content": "Check out our latest articles and insights."},
    ]

    for section_data in new_sections:
        SiteContent.objects.get_or_create(**section_data)

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_new_homepage_sections'),
    ]

    operations = [
        migrations.RunPython(add_new_homepage_sections),
    ]
