# Generated by Django 5.2.8 on 2025-11-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_new_homepage_sections'),
        ('cms', '0008_auto_20240523_1239'),
    ]

    operations = [
    ]
