# Generated by Django 4.x.x on 2025-11-21 12:00

from django.db import migrations

def create_homepage_data(apps, schema_editor):
    SiteContent = apps.get_model('cms', 'SiteContent')

    homepage_content = [
        # Hero Section
        {"page": "home", "section": "hero_title", "title": "Innovate, Automate, Elevate: Your Financial Future, Powered by AI"},
        {"page": "home", "section": "hero_text", "content": "Unlock unparalleled efficiency and strategic insights with XpertAI Global's cutting-edge financial automation. We fuse AI with expert knowledge to transform your accounting, audit, tax, and CFO services."},
        # Assuming an image exists, no content here as it's handled by image field

        # Services Preview
        {"page": "home", "section": "services_title", "title": "Our Transformative Service Pillars"},
        {"page": "home", "section": "service1_title", "title": "Virtual CFO: Strategic Financial Leadership"},
        {"page": "home", "section": "service1_desc", "content": "Gain executive-level financial guidance without the overhead. Our Virtual CFOs drive growth, optimize cash flow, and ensure robust financial health through AI-driven analytics."},
        {"page": "home", "section": "service2_title", "title": "Audit & Assurance: Unquestionable Transparency & Compliance"},
        {"page": "home", "section": "service2_desc", "content": "Secure your operations with meticulous audits and comprehensive assurance services. We leverage AI for fraud detection and precision, ensuring regulatory adherence and stakeholder trust."},
        {"page": "home", "section": "service3_title", "title": "Taxation Services: Intelligent Compliance & Optimization"},
        {"page": "home", "section": "service3_desc", "content": "Navigate the complexities of GST, TDS, and ITR with AI-powered accuracy. Minimize liabilities and maximize returns through our proactive tax planning and compliance solutions."},

        # Features/Benefits Section
        {"page": "home", "section": "features_title", "title": "Why XpertAI Global is Your Strategic Advantage"},
        {"page": "home", "section": "feature1_title", "title": "Hyper-Automation with AI"},
        {"page": "home", "section": "feature1_desc", "content": "Revolutionize your workflows. Our proprietary AI engines automate repetitive tasks, reduce human error, and free up your team for strategic initiatives. Experience efficiency like never before."},
        {"page": "home", "section": "feature2_title", "title": "Unified Intelligence Dashboards"},
        {"page": "home", "section": "feature2_desc", "content": "Visualize your entire financial landscape in real-time. Our intuitive, customizable dashboards provide actionable insights, enabling rapid, informed decision-making across all departments."},
        {"page": "home", "section": "feature3_title", "title": "Bank-Grade Secure Document Management"},
        {"page": "home", "section": "feature3_desc", "content": "Protect your sensitive financial data with state-of-the-art encryption and access controls. Ensure compliance and audit readiness with our robust, AI-monitored document ecosystem."},

        # How It Works
        {"page": "home", "section": "how_it_works_title", "title": "Our Seamless Transformation Journey"},
        {"page": "home", "section": "step1_title", "title": "Discovery & Strategy Alignment"},
        {"page": "home", "section": "step1_desc", "content": "We begin with a deep dive into your current financial ecosystem, identifying pain points and mapping a bespoke AI-driven solution tailored to your unique business objectives."},
        {"page": "home", "section": "step2_title", "title": "AI-Powered Implementation & Integration"},
        {"page": "home", "section": "step2_desc", "content": "Our experts meticulously deploy and integrate advanced AI tools into your existing infrastructure, ensuring a smooth transition and minimal disruption to your operations."},
        {"page": "home", "section": "step3_title", "title": "Continuous Optimization & Growth Partnership"},
        {"page": "home", "section": "step3_desc", "content": "Beyond implementation, we provide ongoing support, performance monitoring, and iterative enhancements, ensuring your financial operations continuously evolve and excel."},

        # Our Mission
        {"page": "home", "section": "our_mission_title", "title": "Our Mission: Propelling Businesses to AI-Driven Financial Zenith"},
        {"page": "home", "section": "our_mission_text", "content": "To empower global enterprises with unparalleled financial agility and foresight through pioneering AI solutions. We are dedicated to redefining efficiency, ensuring compliance, and fostering sustainable growth for every client."},

        # Our Vision
        {"page": "home", "section": "our_vision_title", "title": "Our Vision: The Future of Finance, Intelligent and Limitless"},
        {"page": "home", "section": "our_vision_text", "content": "To be the indispensable global leader in AI-powered financial transformation, envisioning a world where every business, regardless of size, navigates its financial landscape with absolute clarity, precision, and strategic advantage."},

        # Our Commitment
        {"page": "home", "section": "our_commitment_title", "title": "Our Unwavering Commitment: Your Success, Our Mandate"},
        {"page": "home", "section": "our_commitment_text", "content": "We pledge to deliver not just solutions, but enduring partnerships built on trust, innovation, and an unwavering dedication to your financial prosperity. Your challenges are our catalysts for creating groundbreaking AI-driven excellence."},

        # Call to Action
        {"page": "home", "section": "cta_title", "title": "Ready to Redefine Your Financial Horizon?"},
        {"page": "home", "section": "cta_button", "content": "Initiate Your AI Transformation"},

        # Adding new sections to demonstrate adding "as much data as possible"
        {"page": "home", "section": "additional_info_header", "title": "Beyond Numbers: The XpertAI Difference"},
        {"page": "home", "section": "additional_info_paragraph1", "content": "At XpertAI Global, we believe that finance is more than just numbers—it's the heartbeat of your business. Our platforms are designed to provide a holistic view, integrating disparate data sources into a cohesive, intelligent framework."},
        {"page": "home", "section": "additional_info_paragraph2", "content": "Our team of seasoned financial experts and AI specialists work in synergy, bringing a human touch to advanced technology. We pride ourselves on understanding your unique operational DNA and crafting solutions that resonate with your strategic vision."},
        {"page": "home", "section": "core_values_statement", "title": "Innovation. Integrity. Impact."},
        {"page": "home", "section": "core_values_description", "content": "These are the pillars upon which XpertAI Global is built. We relentlessly pursue innovation, uphold the highest standards of integrity, and strive to create a tangible, positive impact on every client's financial journey."},
        {"page": "home", "section": "client_success_stories_intro", "title": "Real Transformations, Real Results"},
        {"page": "home", "section": "client_success_stories_text", "content": "Explore our curated collection of success stories where businesses like yours achieved unprecedented growth, optimized costs, and gained superior financial control with XpertAI Global. Your success narrative is next."},
    ]

    for data in homepage_content:
        SiteContent.objects.update_or_create(
            page=data["page"],
            section=data["section"],
            defaults={
                "title": data.get("title", ""),
                "content": data.get("content", ""),
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_20251121_1253'),
    ]

    operations = [
        migrations.RunPython(create_homepage_data),
    ]
