# Generated by Django 4.x.x on 2025-11-21 13:00

from django.db import migrations

def add_more_homepage_sections_data(apps, schema_editor):
    SiteContent = apps.get_model('cms', 'SiteContent')

    new_homepage_content = [
        # New Section 1: Why Choose Us? (More detailed)
        {"page": "home", "section": "why_choose_us_title", "title": "Why XpertAI Global Stands Apart"},
        {"page": "home", "section": "why_choose_us_feature1_title", "title": "Unrivaled AI Integration"},
        {"page": "home", "section": "why_choose_us_feature1_desc", "content": "Our solutions are not just AI-enhanced; they are AI-native, built from the ground up to leverage the full power of artificial intelligence for superior accuracy and predictive analytics."},
        {"page": "home", "section": "why_choose_us_feature2_title", "title": "Expert Human Oversight"},
        {"page": "home", "section": "why_choose_us_feature2_desc", "content": "Behind every algorithm is a team of certified financial experts and strategists, ensuring that technology serves your specific business context with intelligent human guidance."},
        {"page": "home", "section": "why_choose_us_feature3_title", "title": "Scalable & Future-Proof Solutions"},
        {"page": "home", "section": "why_choose_us_feature3_desc", "content": "Designed for growth, our platforms scale seamlessly with your business, adapting to evolving market demands and technological advancements, keeping you ahead of the curve."},

        # New Section 2: Our Philosophy
        {"page": "home", "section": "our_philosophy_title", "title": "Our Guiding Philosophy"},
        {"page": "home", "section": "our_philosophy_intro", "content": "At XpertAI Global, our ethos is rooted in three core principles: Innovation, Transparency, and Partnership. These values drive every decision and every solution we craft."},
        {"page": "home", "section": "our_philosophy_innovation", "title": "Innovation Driven"},
        {"page": "home", "section": "our_philosophy_innovation_desc", "content": "We continuously push the boundaries of financial technology, integrating the latest AI and machine learning advancements to deliver groundbreaking solutions."},
        {"page": "home", "section": "our_philosophy_transparency", "title": "Transparency Guaranteed"},
        {"page": "home", "section": "our_philosophy_transparency_desc", "content": "We believe in clear communication and complete visibility into your financial data and our processes, fostering trust and empowering informed decisions."},

        # New Section 3: More Client Testimonials
        {"page": "home", "section": "testimonial2_text", "content": "The transition to XpertAI Global's platform was seamless, and the impact on our financial reporting accuracy was immediate. A truly invaluable partner!"},
        {"page": "home", "section": "testimonial2_author", "title": "- Sarah Chen, CFO of Global Innovators"},
        {"page": "home", "section": "testimonial3_text", "content": "Their taxation services saved us a significant amount while ensuring full compliance. The AI insights are game-changing. Highly recommend!"},
        {"page": "home", "section": "testimonial3_author", "title": "- Michael V., Founder of Tech Solutions Inc."},

        # New Section 4: Awards and Recognition
        {"page": "home", "section": "awards_title", "title": "Awards & Recognition"},
        {"page": "home", "section": "award1_year", "title": "2024"},
        {"page": "home", "section": "award1_desc", "content": "AI Innovation Award for Financial Automation Excellence"},
        {"page": "home", "section": "award2_year", "title": "2023"},
        {"page": "home", "section": "award2_desc", "content": "Top FinTech Solution Provider (APAC Region)"},
        {"page": "home", "section": "award3_year", "title": "2022"},
        {"page": "home", "section": "award3_desc", "content": "Excellence in Virtual CFO Services"},

        # New Section 5: Partnerships
        {"page": "home", "section": "partnerships_title", "title": "Our Valued Ecosystem Partners"},
        {"page": "home", "section": "partnership1_name", "title": "GlobalTech Solutions"},
        {"page": "home", "section": "partnership1_desc", "content": "Collaborating to bring advanced cloud infrastructure and data security to our clients."},
        {"page": "home", "section": "partnership2_name", "title": "FinAnalytics Group"},
        {"page": "home", "section": "partnership2_desc", "content": "Strategic alliance for deep-dive financial modeling and market intelligence."},
    ]

    for data in new_homepage_content:
        SiteContent.objects.update_or_create(
            page=data["page"],
            section=data["section"],
            defaults={
                "title": data.get("title", ""),
                "content": data.get("content", ""),
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_populate_homepage_data'),
    ]

    operations = [
        migrations.RunPython(add_more_homepage_sections_data),
    ]
