# Generated by Django 5.0.3 on 2024-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_more_homepage_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='section_name',
            field=models.CharField(default='default section name', help_text="A descriptive name for the content section (e.g., 'Hero Title').", max_length=100),
            preserve_default=False,
        ),
    ]
