# Generated by Django 5.2.8 on 2025-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_add_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(editable=False, help_text='The slug for this section, auto-generated from the section name.', max_length=100),
        ),
    ]
