# Generated by Django 5.2.8 on 2025-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_sitecontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='content_order',
            field=models.PositiveIntegerField(default=0, editable=False, db_index=True),
        ),
    ]
