# Generated by Django 5.2.8 on 2025-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_add_content_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('result_stat', models.CharField(help_text="e.g. '40% ROI Increase'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='casestudies/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='casestudies/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Whitepaper', 'Whitepaper'), ('E-Book', 'E-Book'), ('Guide', 'Guide')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: About',
                'verbose_name_plural': 'Page: About Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.CreateModel(
            name='CareersContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Careers',
                'verbose_name_plural': 'Page: Careers Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Contact',
                'verbose_name_plural': 'Page: Contact Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Home',
                'verbose_name_plural': 'Page: Home Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.CreateModel(
            name='ResourcesContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Resources',
                'verbose_name_plural': 'Page: Resources Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.CreateModel(
            name='ServicesContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Services',
                'verbose_name_plural': 'Page: Services Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['content_order']},
        ),
    ]
