# Generated by Django 5.2.8 on 2025-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_casestudy_resource_aboutcontent_careerscontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Virtual CFO', max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name, e.g. virtual-cfo', unique=True)),
                ('short_description', models.TextField(help_text='Shown on the main Services page card')),
                ('full_description', models.TextField(help_text='Shown on the detailed service page. HTML allowed.')),
                ('icon', models.CharField(default='Briefcase', help_text='Icon name (e.g. Briefcase, BarChart)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
