# Generated by Django 5.2.8 on 2025-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (Browser Tab)', max_length=255),
        ),
    ]
