# Generated by Django 5.2.8 on 2025-11-22 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_page_keywords_page_meta_description_page_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(help_text='Upload your document here (PDF, Excel, CSV, PPT, Word, etc.)', upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xlsx', 'xls', 'ppt', 'pptx', 'doc', 'docx', 'txt', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Whitepaper', 'Whitepaper'), ('E-Book', 'E-Book'), ('Guide', 'Guide'), ('Report', 'Report'), ('Presentation', 'Presentation'), ('Dataset', 'Dataset')], max_length=50),
        ),
    ]
