# Generated by Django 5.2.8 on 2025-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_resource_file_alter_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Page: Footer',
                'verbose_name_plural': 'Page: Footer Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sitecontent',),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('features', 'Features'), ('stakeholders', 'Stakeholders'), ('lead_system', 'Lead System'), ('blog', 'Blog'), ('resources', 'Resources'), ('careers', 'Careers'), ('contact', 'Contact'), ('portfolio', 'Portfolio'), ('footer', 'Footer')], max_length=50),
        ),
    ]
