# Generated by Django 5.2.8 on 2025-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_footercontent_alter_sitecontent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
