# Generated by Django 5.2.8 on 2025-12-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_page_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, help_text='Optional intro text shown on the detail page before the list.', null=True),
        ),
        migrations.CreateModel(
            name='ServiceSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 1. Statutory & Tax Audits', max_length=200)),
                ('description', models.TextField(help_text='Detailed explanation of this sub-service.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='cms.service')),
            ],
            options={
                'verbose_name': 'Service Sub-Point',
                'verbose_name_plural': 'Service Sub-Points',
                'ordering': ['order'],
            },
        ),
    ]
