# Generated by Django 5.2.8 on 2025-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Next-Gen Financial Intelligence', max_length=255)),
                ('hero_subtitle', models.TextField(default='Automate audits, tax compliance, and forecasting with AI precision.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('hero_cta_text', models.CharField(default='Start Free Trial', max_length=50)),
                ('clients_title', models.CharField(blank=True, default='Trusted by Industry Leaders', max_length=255)),
                ('process_title', models.CharField(blank=True, default='How It Works', max_length=255)),
                ('process_subtitle', models.TextField(blank=True, default='Seamless integration in 3 simple steps.')),
                ('features_title', models.CharField(blank=True, default='Why Choose XpertAI?', max_length=255)),
                ('reviews_title', models.CharField(blank=True, default='Client Success Stories', max_length=255)),
                ('faq_title', models.CharField(blank=True, default='Frequently Asked Questions', max_length=255)),
                ('cta_title', models.CharField(default='Ready to Transform?', max_length=255)),
                ('cta_text', models.TextField(default='Join 500+ companies streamlining their finance today.')),
                ('cta_btn_text', models.CharField(default='Get Started', max_length=50)),
            ],
            options={
                'verbose_name': 'Home Page Setup',
                'verbose_name_plural': 'Home Page Setup',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Settings', help_text='Lucide Icon Name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='BottomCTA',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon_name',
            field=models.CharField(default='TrendingUp', max_length=50),
        ),
    ]
