# Generated by Django 5.2.8 on 2026-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_faq_homepagecontent_processstep_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_btn_link',
            field=models.CharField(default='/contact', max_length=100),
        ),
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='Users', max_length=50),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='icon_name',
            field=models.CharField(default='Settings', max_length=50),
        ),
    ]
