# Generated by Django 5.2.8 on 2026-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepagecontent_cta_btn_link_stat_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='cta_btn_link',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='cta_btn_text',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='features_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='ai_subtitle',
            field=models.CharField(blank=True, default='Let our AI-powered selector guide you.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='ai_title',
            field=models.CharField(blank=True, default='Not sure where to start?', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_cta_link',
            field=models.CharField(blank=True, default='/contact', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_sec_btn_text',
            field=models.CharField(blank=True, default='How It Works', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_1_link',
            field=models.CharField(blank=True, default='/contact', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_1_text',
            field=models.CharField(blank=True, default='Sign Up', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_2_link',
            field=models.CharField(blank=True, default='/services', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_2_text',
            field=models.CharField(blank=True, default='Explore Services', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_3_link',
            field=models.CharField(blank=True, default='/careers', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_link_3_text',
            field=models.CharField(blank=True, default='Join as Professional', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_title',
            field=models.CharField(blank=True, default='Our Key Services', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stories_title',
            field=models.CharField(blank=True, default='Success Stories', max_length=255),
        ),
    ]
