# Generated by Django 5.2.8 on 2025-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSBottomCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Streamline?', max_length=255)),
                ('text', models.TextField(default='Join the platform that powers high-growth teams.')),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
            ],
            options={
                'verbose_name': 'Bottom CTA',
                'verbose_name_plural': 'Bottom CTA',
            },
        ),
        migrations.CreateModel(
            name='LSFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Target', help_text='Lucide Icon Name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LSHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lead Management System', max_length=255)),
                ('subtitle', models.TextField(default='Track, Manage, and Convert leads with AI precision.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
