# Generated by Django 5.2.8 on 2025-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_system_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload the Dashboard Preview Image here', null=True, upload_to='lead_system/')),
                ('placeholder_text', models.CharField(default='Dashboard Preview', help_text='Alt text for the image', max_length=255)),
            ],
            options={
                'verbose_name': 'Dashboard Preview',
                'verbose_name_plural': 'Dashboard Preview',
            },
        ),
    ]
