# Generated by Django 5.2.8 on 2025-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Clients, Investors', max_length=200)),
                ('description', models.TextField(help_text='Short description about this stakeholder group.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='stakeholders/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order on the website')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
