# Generated by Django 5.2.8 on 2025-12-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['order'], 'verbose_name': 'Solution Category', 'verbose_name_plural': 'Solution Categories'},
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='icon',
            new_name='image',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='icon_name',
            field=models.CharField(default='Users', help_text='Lucide Icon Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
