# Generated by Django 5.2.8 on 2025-12-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_stakeholder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Solutions', max_length=255)),
                ('hero_subtitle', models.TextField(default='Tailored ecosystems for every stakeholder in the financial world.')),
                ('cta_title', models.CharField(default='Ready to join the ecosystem?', max_length=255)),
                ('cta_text', models.TextField(default='Whether you are a client looking for experts or a professional seeking work, XpertAI has a place for you.')),
                ('cta_btn_primary', models.CharField(default='Sign Up Now', max_length=50)),
                ('cta_btn_secondary', models.CharField(default='Contact Sales', max_length=50)),
            ],
            options={
                'verbose_name': 'Solutions Page Setup',
                'verbose_name_plural': 'Solutions Page Setup',
            },
        ),
    ]
