# Generated by Django 5.2.8 on 2025-12-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_solutionspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutionspage',
            options={'verbose_name': 'Solutions Page Content', 'verbose_name_plural': 'Solutions Page Content'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['order'], 'verbose_name': 'Solution Card', 'verbose_name_plural': 'Solution Cards'},
        ),
        migrations.AlterField(
            model_name='solutionspage',
            name='cta_title',
            field=models.CharField(default='Ready to join the ecosystem?', max_length=200),
        ),
        migrations.AlterField(
            model_name='solutionspage',
            name='hero_title',
            field=models.CharField(default='Our Solutions', max_length=200),
        ),
    ]
