# Generated by Django 5.2.8 on 2025-12-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_alter_solutionspage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed content for the new page'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier (auto-generated from title)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='description',
            field=models.TextField(help_text='Short description for the card'),
        ),
    ]
