# Generated by Django 5.2.8 on 2026-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_stakeholder_long_description_stakeholder_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='description',
            field=models.TextField(help_text='Short summary shown on the card'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='icon_name',
            field=models.CharField(default='Layers', help_text='Lucide Icon Name (e.g. Layers, Briefcase)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed text for the individual solution page'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
