# Generated by Django 5.2.8 on 2025-12-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Zap', help_text='Lucide Icon Name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Build the Future of Finance', max_length=255)),
                ('hero_subtitle', models.TextField(default='Join a team of visionaries, engineers, and financial experts redefining the global economy.')),
                ('benefits_title', models.CharField(default='Why Join XpertAI?', max_length=255)),
                ('benefits_subtitle', models.TextField(default='Perks that help you grow, learn, and thrive.')),
                ('culture_title', models.CharField(default='Our Culture', max_length=255)),
                ('culture_text', models.TextField(default='We believe in autonomy, mastery, and purpose. Work from anywhere, own your projects, and make a dent in the universe.')),
                ('culture_image', models.ImageField(blank=True, null=True, upload_to='careers/')),
                ('openings_title', models.CharField(default='Current Openings', max_length=255)),
            ],
            options={
                'verbose_name': 'Careers Page Setup',
                'verbose_name_plural': 'Careers Page Setup',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(help_text='Link to Google Drive/Dropbox file'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=models.TextField(help_text='HTML Allowed'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
