# Generated by Django 5.2.8 on 2025-12-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_benefit_careerspage_jobapplication_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='careerspage',
            name='culture_text',
            field=models.TextField(default='We believe in autonomy, mastery, and purpose.'),
        ),
    ]
