# Generated by Django 5.2.8 on 2025-12-13 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_employeetestimonial_alter_careerspage_culture_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload Resume (PDF Only)', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Optional Link to Resume (Google Drive/Dropbox)', null=True),
        ),
    ]
