# Generated by Django 5.2.8 on 2026-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobapplication_resume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerspage',
            name='form_cover_letter_label',
            field=models.CharField(default='Cover Letter', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_email_label',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_linkedin_label',
            field=models.CharField(default='LinkedIn URL', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_name_label',
            field=models.CharField(default='Full Name', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_phone_label',
            field=models.CharField(default='Phone', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_referral_label',
            field=models.CharField(default='How did you hear about us?', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='form_resume_label',
            field=models.CharField(default='Resume (PDF)', max_length=100),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='is_cover_letter_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='is_linkedin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='is_phone_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='is_referral_multiselect',
            field=models.BooleanField(default=False, help_text='If checked, allows multiple selections.'),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='referral_options',
            field=models.TextField(default='LinkedIn,Glassdoor,Referral,Twitter,Other', help_text='Comma-separated values'),
        ),
        migrations.AddField(
            model_name='careerspage',
            name='show_referral_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_source',
            field=models.TextField(blank=True, help_text='Captured from dynamic form field', null=True),
        ),
    ]
