# Generated by Django 5.2.8 on 2025-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('slug', models.SlugField(help_text='A unique name for the page, used to identify it.', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='The main title of the page.', max_length=200)),
                ('content', models.TextField(blank=True, help_text='The main content of the page. Can include HTML.')),
            ],
        ),
    ]
