# Generated by Django 5.2.8 on 2025-11-28 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('result_stat', models.CharField(help_text="e.g. '40% ROI Increase'", max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='case_studies/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Whitepaper', 'Whitepaper'), ('E-Book', 'E-Book'), ('Guide', 'Guide'), ('Report', 'Report'), ('Dataset', 'Dataset')], default='Guide', max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='downloads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xlsx', 'ppt', 'docx', 'zip'])])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Download Item',
                'verbose_name_plural': 'Download Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourcesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Knowledge Center', max_length=255)),
                ('subtitle', models.TextField(default='Insights, downloads, and success stories.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='SectionTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_studies_title', models.CharField(default='Success Stories', max_length=100)),
                ('downloads_title', models.CharField(default='Downloads', max_length=100)),
            ],
            options={
                'verbose_name': 'Section Titles',
                'verbose_name_plural': 'Section Titles',
            },
        ),
    ]
