# Generated by Django 5.2.8 on 2025-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='downloadableresource',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='downloadableresource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional: Link to external article/resource', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='casestudies/'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='result_stat',
            field=models.CharField(help_text="e.g. '300% Growth'", max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadableresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='downloadableresource',
            name='resource_type',
            field=models.CharField(choices=[('E-Book', 'E-Book'), ('Whitepaper', 'Whitepaper'), ('Guide', 'Guide'), ('Report', 'Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resourceshero',
            name='subtitle',
            field=models.TextField(default='Expert insights, whitepapers, and success stories to guide your financial strategy.'),
        ),
        migrations.AlterField(
            model_name='resourceshero',
            name='title',
            field=models.CharField(default='Knowledge Hub', max_length=255),
        ),
        migrations.AlterField(
            model_name='sectiontitles',
            name='case_studies_title',
            field=models.CharField(default='Client Success Stories', max_length=255),
        ),
        migrations.AlterField(
            model_name='sectiontitles',
            name='downloads_title',
            field=models.CharField(default='Essential Downloads', max_length=255),
        ),
    ]
