# Generated by Django 5.2.8 on 2025-12-01 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_page', '0002_alter_casestudy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableresource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional: Link to external article/resource if no file is uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='downloadableresource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload your document here (PDF, Excel, CSV, PPT, Word, etc.)', null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xlsx', 'xls', 'ppt', 'pptx', 'doc', 'docx', 'txt', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='downloadableresource',
            name='resource_type',
            field=models.CharField(choices=[('E-Book', 'E-Book'), ('Whitepaper', 'Whitepaper'), ('Guide', 'Guide'), ('Report', 'Report'), ('Presentation', 'Presentation'), ('Dataset', 'Dataset')], max_length=50),
        ),
    ]
