# Generated by Django 5.2.8 on 2025-12-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_page', '0003_alter_downloadableresource_external_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'ICAI Official Website'", max_length=255)),
                ('url', models.URLField(help_text='External URL (e.g. https://www.icai.org/)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Useful Link',
                'verbose_name_plural': 'Useful Links',
                'ordering': ['order'],
            },
        ),
    ]
