# Generated by Django 5.2.8 on 2025-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('primary_color', models.CharField(default='#1c1c1c', max_length=7)),
                ('secondary_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('accent_color', models.CharField(default='#007bff', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#343a40', max_length=7)),
                ('heading_color', models.CharField(default='#000000', max_length=7)),
                ('link_color', models.CharField(default='#007bff', max_length=7)),
                ('footer_background_color', models.CharField(default='#1c1c1c', max_length=7)),
                ('footer_text_color', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Theme',
            },
        ),
    ]
