# Generated by Django 5.0 on 2025-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('light_primary_color', models.CharField(default='#1c1c1c', max_length=7)),
                ('light_secondary_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('light_accent_color', models.CharField(default='#007bff', max_length=7)),
                ('light_background_color', models.CharField(default='#ffffff', max_length=7)),
                ('light_text_color', models.CharField(default='#343a40', max_length=7)),
                ('dark_primary_color', models.CharField(default='#ffffff', max_length=7)),
                ('dark_secondary_color', models.CharField(default='#343a40', max_length=7)),
                ('dark_accent_color', models.CharField(default='#007bff', max_length=7)),
                ('dark_background_color', models.CharField(default='#1c1c1c', max_length=7)),
                ('dark_text_color', models.CharField(default='#f8f9fa', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
