# Generated by Django 5.2.8 on 2025-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_themesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='dark_accent_color',
            field=models.CharField(default='#10B981', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='dark_background_color',
            field=models.CharField(default='#111827', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='dark_primary_color',
            field=models.CharField(default='#34D399', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='dark_secondary_color',
            field=models.CharField(default='#FBBF24', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='dark_text_color',
            field=models.CharField(default='#F3F4F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='light_accent_color',
            field=models.CharField(default='#059669', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='light_background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='light_primary_color',
            field=models.CharField(default='#10B981', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='light_secondary_color',
            field=models.CharField(default='#F59E0B', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='light_text_color',
            field=models.CharField(default='#1F2937', max_length=7),
        ),
    ]
