# Generated by Django 5.2.8 on 2025-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_delete_theme_alter_themesetting_dark_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a transparent PNG logo for Header & Footer', null=True, upload_to='site_config/'),
        ),
    ]
