# Generated by Django 5.2.8 on 2025-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_themesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='chatbot_welcome_message',
            field=models.TextField(default='👋 Hi! I’m XpertAI Assistant. How can I help you today?', help_text='Initial message shown by the chatbot.'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='contact_email',
            field=models.EmailField(default='hello@xpertai.global', help_text='Email shown in Header/Footer', max_length=254),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='contact_phone',
            field=models.CharField(default='+91 98765 43210', help_text='Phone number shown in Header/Footer', max_length=20),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn Company Page URL'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X Profile URL'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a transparent PNG logo', null=True, upload_to='site_config/'),
        ),
    ]
