# Generated by Django 5.2.8 on 2025-11-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_themesetting_chatbot_welcome_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='contact_email',
            field=models.EmailField(default='hello@xpertai.global', help_text='Email address for Header/Footer', max_length=254),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='contact_phone',
            field=models.CharField(default='+91 98765 43210', help_text='Phone number for Header/Footer', max_length=20),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a transparent PNG logo for Header & Footer', null=True, upload_to='site_config/'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X URL'),
        ),
    ]
