# Generated by Django 5.2.8 on 2025-11-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_alter_themesetting_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to True to make this theme live on the website. Only one theme can be active.'),
        ),
    ]
