# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_themesetting_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text="The question the bot asks (e.g., 'What is your name?').", max_length=255)),
                ('field_to_save', models.CharField(choices=[('name', 'Applicant Name'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('service', 'Service Interest'), ('message', 'Message/Final Query')], help_text="The Lead field this question's answer should populate.", max_length=50, unique=True)),
                ('step_order', models.PositiveIntegerField(default=0, help_text='Order in which questions are asked.')),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Flow Step',
                'verbose_name_plural': 'Chatbot Flow Steps',
                'ordering': ['step_order'],
            },
        ),
    ]
