# Generated by Django 5.2.8 on 2025-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_chatbotflowstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeSetting',
        ),
        migrations.AlterField(
            model_name='chatbotflowstep',
            name='question_text',
            field=models.CharField(help_text='The question the bot asks.', max_length=255),
        ),
    ]
