# Generated by Django 5.2.8 on 2025-12-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get in Touch', max_length=255)),
                ('hero_subtitle', models.TextField(default="We'd love to hear from you. Reach out to us for any queries.")),
                ('form_title', models.CharField(default='Send us a Message', max_length=255)),
                ('map_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.792576390356!2d72.87765631490116!3d19.07609098708786!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c6306644edc1%3A0x5da4ed8f8d648c69!2sMumbai%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1625567890123!5m2!1sen!2sin', help_text="Paste the Google Maps Embed iframe 'src' URL here (starts with https://www.google.com/maps/embed...)")),
                ('support_title', models.CharField(default='Support & Assistance', max_length=255)),
                ('support_text', models.TextField(default='Need help? Choose the right channel for a quick resolution.')),
            ],
            options={
                'verbose_name': 'Contact Page Setup',
                'verbose_name_plural': 'Contact Page Setup',
            },
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Corporate Office, Branch Office', max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Query/Message from the user'),
        ),
    ]
