# Generated by Django 5.2.8 on 2026-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_button_text',
            field=models.CharField(default='Request Consultation', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_company_label',
            field=models.CharField(default='Company', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_email_label',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_message_label',
            field=models.CharField(default='Message', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_name_label',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_phone_label',
            field=models.CharField(default='Phone', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_service_label',
            field=models.CharField(default='I am interested in...', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_timeline_label',
            field=models.CharField(default='Timeline', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='is_sub_service_multiselect',
            field=models.BooleanField(default=True, help_text='Uncheck to force users to select only ONE sub-service.'),
        ),
    ]
