# Generated by Django 5.2.8 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About XpertAI Global', max_length=255)),
                ('hero_subtitle', models.TextField(default='Pioneering the future of financial intelligence.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_text', models.TextField(default='To empower businesses with AI-driven financial clarity.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_text', models.TextField(default='A world where finance is automated, accurate, and strategic.')),
                ('values_title', models.CharField(default='Our Values', max_length=255)),
                ('values_text', models.TextField(default='Integrity, Innovation, and Impact.')),
                ('story_title', models.CharField(blank=True, default='Our Story', max_length=255)),
                ('story_text', models.TextField(blank=True, help_text='How we started...')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('global_title', models.CharField(blank=True, default='Global Presence', max_length=255)),
                ('global_stats', models.CharField(blank=True, default='Active in 15+ Countries', max_length=255)),
                ('awards_title', models.CharField(blank=True, default='Awards & Recognition', max_length=255)),
                ('csr_title', models.CharField(blank=True, default='Sustainability', max_length=255)),
                ('csr_text', models.TextField(blank=True, help_text='Our commitment to the planet.')),
                ('cta_title', models.CharField(default='Join Our Journey', max_length=255)),
                ('cta_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page Setup',
                'verbose_name_plural': 'About Page Setup',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
