# Generated by Django 5.2.8 on 2025-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='awards_title',
        ),
        migrations.RemoveField(
            model_name='award',
            name='icon_image',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
