# Generated by Django 5.2.8 on 2025-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutpage_awards_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='awards_title',
            field=models.CharField(blank=True, default='Awards & Recognition', max_length=255),
        ),
        migrations.AddField(
            model_name='award',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='awards/'),
        ),
    ]
