# Generated by Django 5.2.8 on 2025-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_awards_title_award_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Cpu', help_text='Lucide Icon Name (e.g. Cpu, Link, Bot)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology Stack',
                'verbose_name_plural': 'Technology Stack',
                'ordering': ['order'],
            },
        ),
    ]
