# Generated by Django 5.2.8 on 2025-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page Title (e.g. Privacy Policy)', max_length=200)),
                ('slug', models.SlugField(help_text='URL identifier (e.g. privacy-policy, terms)', unique=True)),
                ('content', models.TextField(help_text='Main content. HTML is supported for formatting.')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
