# Generated by Django 5.2.8 on 2025-12-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpage',
            name='content',
        ),
        migrations.AddField(
            model_name='legalpage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional short intro text.'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='slug',
            field=models.SlugField(help_text='URL identifier (e.g. privacy-policy)', unique=True),
        ),
        migrations.CreateModel(
            name='LegalPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Section Heading (e.g. '1. Data Collection')", max_length=255)),
                ('content', models.TextField(help_text='Content for this section.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display (1, 2, 3...)')),
                ('legal_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal.legalpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
