# Generated by Django 5.2.8 on 2025-12-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_remove_legalpage_content_legalpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional short intro text (appears at top).'),
        ),
        migrations.AlterField(
            model_name='legalpagesection',
            name='content',
            field=models.TextField(help_text='Content for this heading.'),
        ),
        migrations.AlterField(
            model_name='legalpagesection',
            name='heading',
            field=models.CharField(help_text="Section Heading (e.g. '1. Introduction')", max_length=255),
        ),
        migrations.AlterField(
            model_name='legalpagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order number (1, 2, 3...)'),
        ),
    ]
