# Generated by Django 5.2.8 on 2025-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_alter_legalpage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalpagesection',
            options={'ordering': ['order'], 'verbose_name': 'Legal Page Section', 'verbose_name_plural': 'Legal Page Sections'},
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='description',
            field=models.TextField(blank=True, help_text='Short Intro Text (Optional)'),
        ),
        migrations.AlterField(
            model_name='legalpagesection',
            name='content',
            field=models.TextField(help_text='Is heading ka content yahan likhein.'),
        ),
        migrations.AlterField(
            model_name='legalpagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sequence number (1, 2, 3...)'),
        ),
    ]
